# Generated by Django 5.1 on 2024-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Feminine')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'DEPENSES(TRANSPORT)'), ('P', 'DEPENSES(MAGASIN)'), ('I', 'DEPENSES PERSONNEL'), ('D', 'AUTRES DEPENSES'), ('F', 'FACTURE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
